### ISSUE TITLE
AWS runner

### ISSUE THREAD

**Issue by tphoney** [drone/proposal#2]
There is an open proposal for the creation of an aws runner. [here](https://github.com/drone/proposal/blob/master/design/01-aws-runner.md) With work going on [here] https://github.com/drone-runners/drone-runner-aws

**Comment by CubicNitrous** [comment]
@tphoney will there be a way to put tags on the AWS instances that are created by the pool? We handle billing internally by tag.

**Comment by tphoney** [comment]
> @tphoney will there be a way to put tags on the AWS instances that are created by the pool? We handle billing internally by tag.

Yes, that functionality is already there. if you look at https://docs.drone.io/runner/aws/configuration/pool/ specifically 
```
---

name: windows 2019
max_pool_size: 1

platform:
 os: windows

account:
  region: us-east-2
  access_key_id: <super-secret>
  access_key_secret: <super-secret>

instance:
  ami: ami-0840994b9b4c03cb1
  type: t2.medium
  network:
    security_groups:
      - sg-00000000
  tags:
    cat: dog
```
