### ISSUE TITLE
Show environment variables for every step of every build in the UI

### ISSUE THREAD

**Issue by djmattyg007** [drone/proposal#25]
Being able to see the environment variables that were used for a particular step can be extremely helpful when debugging issues that occur in CI.

As a workaround, I currently add a step to my pipeline that looks like this (any image will do):

```yaml
kind: "pipeline"
name: "printenv"
clone:
  disable: true
steps:
  - name: "printenv"
    image: "python:3.10"
    commands:
      - "env | sort"
```

However this is annoying to do, and is usually only done retroactively. It's also not complete - it doesn't capture environment variables that may be set for other steps, for example.
