### ISSUE TITLE
Allow use of environment variables in plugin settings

### ISSUE THREAD

**Issue by WillGibson** [drone/proposal#30]
Currently we can use the built in Drone environment variables in plugin settings, e.g...

```
steps:
  - name: some-step
    image: some-plugin-docker-image
    settings:
      some_setting: ${DRONE_TAG}
```

...but not other environment variables, e.g...

```
environment:
  SOME_ENVIRONMENT_VARIABLE: 7.1.0

steps 
  - name: some-step
    image: some-plugin-docker-image
    settings:
      some_setting: ${SOME_ENVIRONMENT_VARIABLE}
```

It would be very useful if we could use other environment variables too.
