### ISSUE TITLE
Add step/pipeline timeout

### ISSUE THREAD

**Issue by andrii-kasparevych** [drone/proposal#33]
Some of the pipeline steps can get hanging for whatever reason (e.g. an agent gets killed w/o server noticing) or one might want to e.g. limit the tests execution time and fail if someone adds a test that runs for too long.
A nice solution for that would be to add a timeout field that you could specify on the pipeline or step level, e.g.
```
---
kind: pipeline
type: docker
name: default
timeout: 1h

steps:
- name: backend
  image: golang
  commands:
  - go build
  - go test
  timeout: 15m

- name: frontend
  image: node
  commands:
  - npm install
  - npm run test
...
```
